export const ERROR_CODES = {
  BAD_REQUEST:         'BAD_REQUEST',
  UNAUTHORIZED:        'UNAUTHORIZED',
  FORBIDDEN:           'FORBIDDEN',
  NOT_FOUND:           'NOT_FOUND',
  CONFLICT:            'CONFLICT',
  VALIDATION_ERROR:    'VALIDATION_ERROR',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  INTERNAL_ERROR:      'INTERNAL_ERROR',
  ACCOUNT_SUSPENDED:   'ACCOUNT_SUSPENDED',
  INVALID_TRANSITION:  'INVALID_TRANSITION',
  TOKEN_EXPIRED:       'TOKEN_EXPIRED',
  TOKEN_INVALID:       'TOKEN_INVALID',
} as const;

export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES];
